const num = fs.readFileSync(__dirname + "/test.txt").toString().trim().split("\n");
const cut = num[0].split(' ');
const a = Number(cut[0]);
const b = Number(cut[1]);
const plus = a + b;
const minus = a - b;
const multiplied  = a * b;
const quotient = Math.floor(a / b);
const reminder = a % b;
plus.toString();
minus.toString();
multiplied.toString();
quotient.toString();
reminder.toString();
const str = plus + "\n" + minus + "\n" + multiplied + "\n" + quotient + "\n" + reminder;
console.log(str);